:sparkles: feat: 벌크 기능 추가

diff --git a/.github/workflows/deploy-admin.yml b/.github/workflows/deploy-admin.yml
--- a/.github/workflows/deploy-admin.yml
+++ b/.github/workflows/deploy-admin.yml
@@ -131,48 +131,48 @@ jobs:
           docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
           docker push $IMAGE_ID:$VERSION
 
-  docker-deploy:
-    needs: [docker-push]
-    runs-on: ubuntu-latest
+  # docker-deploy:
+  #   needs: [docker-push]
+  #   runs-on: ubuntu-latest
 
-    permissions:
-      contents: read
+  #   permissions:
+  #     contents: read
 
-    env:
-      TOAST_NCS_WORKLOAD_ID: e200bf80-f1af-4884-a9ca-785d9f1d8615
+  #   env:
+  #     TOAST_NCS_WORKLOAD_ID: e200bf80-f1af-4884-a9ca-785d9f1d8615
 
-    steps:
-      - name: Get Toast Cloud Token
-        id: authorize-toast
-        run: |
-          response=$(curl -s -X POST https://oauth.api.nhncloudservice.com/oauth2/token/create \
-            -u "${{ secrets.TOAST_ACCESS_KEY_ID }}:${{ secrets.TOAST_SECRET_ACCESS_KEY }}" \
-            -H "Content-Type: application/x-www-form-urlencoded" \
-            -d "grant_type=client_credentials")
+  #   steps:
+  #     - name: Get Toast Cloud Token
+  #       id: authorize-toast
+  #       run: |
+  #         response=$(curl -s -X POST https://oauth.api.nhncloudservice.com/oauth2/token/create \
+  #           -u "${{ secrets.TOAST_ACCESS_KEY_ID }}:${{ secrets.TOAST_SECRET_ACCESS_KEY }}" \
+  #           -H "Content-Type: application/x-www-form-urlencoded" \
+  #           -d "grant_type=client_credentials")
 
-          access_token=$(echo "$response" | jq -r '.access_token')
+  #         access_token=$(echo "$response" | jq -r '.access_token')
 
-          if [ -n "$access_token" ] && [ "$access_token" != "null" ]; then
-            echo "TOAST_ACCESS_TOKEN=$access_token" >> $GITHUB_OUTPUT
-            echo "✅ Access token retrieved and stored in environment."
-          else
-            echo "❌ Failed to retrieve access token."
-            exit 1
-          fi
+  #         if [ -n "$access_token" ] && [ "$access_token" != "null" ]; then
+  #           echo "TOAST_ACCESS_TOKEN=$access_token" >> $GITHUB_OUTPUT
+  #           echo "✅ Access token retrieved and stored in environment."
+  #         else
+  #           echo "❌ Failed to retrieve access token."
+  #           exit 1
+  #         fi
 
-      - name: Stop previous Toast NCS deployment
-        run: |
-          curl -X POST https://kr1-ncs.api.nhncloudservice.com/ncs/v1.0/appkeys/${{ secrets.TOAST_NCS_API_KEY }}/workloads/${{ env.TOAST_NCS_WORKLOAD_ID }}/pause \
-            -H "x-nhn-authorization: Bearer ${{ steps.authorize-toast.outputs.TOAST_ACCESS_TOKEN }}"
+  #     - name: Stop previous Toast NCS deployment
+  #       run: |
+  #         curl -X POST https://kr1-ncs.api.nhncloudservice.com/ncs/v1.0/appkeys/${{ secrets.TOAST_NCS_API_KEY }}/workloads/${{ env.TOAST_NCS_WORKLOAD_ID }}/pause \
+  #           -H "x-nhn-authorization: Bearer ${{ steps.authorize-toast.outputs.TOAST_ACCESS_TOKEN }}"
 
-      - name: Trigger Toast NCS deployment
-        run: |
-          curl -X POST https://kr1-ncs.api.nhncloudservice.com/ncs/v1.0/appkeys/${{ secrets.TOAST_NCS_API_KEY }}/workloads/${{ env.TOAST_NCS_WORKLOAD_ID }}/resume \
-            -H "x-nhn-authorization: Bearer ${{ steps.authorize-toast.outputs.TOAST_ACCESS_TOKEN }}"
+  #     - name: Trigger Toast NCS deployment
+  #       run: |
+  #         curl -X POST https://kr1-ncs.api.nhncloudservice.com/ncs/v1.0/appkeys/${{ secrets.TOAST_NCS_API_KEY }}/workloads/${{ env.TOAST_NCS_WORKLOAD_ID }}/resume \
+  #           -H "x-nhn-authorization: Bearer ${{ steps.authorize-toast.outputs.TOAST_ACCESS_TOKEN }}"
 
-      - name: Invalidate (Revoke) used Toast Cloud Token
-        run: |
-          curl -X POST https://oauth.api.nhncloudservice.com/oauth2/token/revoke \
-            -u "${{ secrets.TOAST_ACCESS_KEY_ID }}:${{ secrets.TOAST_SECRET_ACCESS_KEY }}" \
-            -H "Content-Type: application/x-www-form-urlencoded" \
-            -d "token=${{ steps.authorize-toast.outputs.TOAST_ACCESS_TOKEN }}"
+  #     - name: Invalidate (Revoke) used Toast Cloud Token
+  #       run: |
+  #         curl -X POST https://oauth.api.nhncloudservice.com/oauth2/token/revoke \
+  #           -u "${{ secrets.TOAST_ACCESS_KEY_ID }}:${{ secrets.TOAST_SECRET_ACCESS_KEY }}" \
+  #           -H "Content-Type: application/x-www-form-urlencoded" \
+  #           -d "token=${{ steps.authorize-toast.outputs.TOAST_ACCESS_TOKEN }}"
